version: "3.9"

services:

  # POSTGRES DATABASE
  db:
    image: postgres:16
    container_name: irrigo_postgres
    restart: always

    environment:
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_password
      POSTGRES_DB: irrigo_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - irrigo_net


  # FASTAPI BACKEND
  backend:
    build: .
    container_name: irrigo_backend
    #restart: always

    depends_on:
      - db

    environment:
      PYTHONDONTWRITEBYTECODE: 1
      DATABASE_URL: postgresql+psycopg2://iot_user:iot_password@db:5432/irrigo_db
      SECRET_KEY: super-secret-key
      DEVICE_API_KEY_SECRET: esp32-secret

    ports:
      - "8000:8000"

    volumes:
      - .:/backend

    command: >
      uvicorn backend.main:app
      --host 0.0.0.0
      --port 8000
      --reload

    networks:
      - irrigo_net


volumes:
  postgres_data:


networks:
  irrigo_net: